/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6e7d480ef9a9936780b05726bade73ab)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		DATABASE: D1Database;
		ASSETS: Fetcher;
		PASSWORD_WORK_FACTOR: 12;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PASSWORD_WORK_FACTOR">> {}
}
